#pragma once

enum ImGuiWindowFlag
{
	IMWINDOW_FLAG_NONE = 0,
	IMWINDOW_FLAG_FIXED_WINDOW_SIZE = 1 << 0,
	IMWINDOW_FLAG_FIXED_WINDOW_POSITION = 1 << 1,
	IMWINDOW_FLAG_NO_CLOSE_BUTTON = 1 << 2,
	IMWINDOW_FLAG_NO_PADDING = 1 << 3,
	IMWINDOW_FLAG_ALWAYS_TABBAR = 1 << 4,
};

enum ImGuiDockWindowFlag
{
	IMDOCKWINDOW_FLAG_NONE = 0,
	IMDOCKWINDOW_FLAG_FULLSCREEN = 1 << 0,
	IMDOCKWINDOW_FLAG_PADDING = 1 << 1,
};